name: Create new release on pushed tag

on: {}
  # push:
  #   tags:
  #   - '*'

jobs:
  build-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Tailscale build container
        run: make build-tailscaled-container

      - name: Create QDK build container
        run: make build-qdk-container

      - name: Create Tailscale QPKG
        run : make out/pkg

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "out/pkg/*.qpkg"
          token: ${{ secrets.GITHUB_TOKEN }}
